#INGRESE EL NUMERO DE HORAS TRABAJADAS Y EL COSTO POR HORAS. CALCULAR EL PAGO TOTAL.

hr= int(input("INGRESE EL NUMERO DE HORAS TRABAJADAS: "))
cst=float(input ( "INGRESE EL COSTO POR HORAS"))
pagoTotal = hr*cst
print ("EL PAGO TOTAL ES DE: ", pagoTotal);